### ISSUE TITLE
Is the website broken?

### ISSUE THREAD

**Issue by akatechis** [doctorn/micro-mitten#1]
I go to https://mitten-lang.org/ but all I see is a pulsating logo. No errors in my console, I do see the javascript and CSS bundles getting downloaded but nothing really happens.

![image](https://user-images.githubusercontent.com/1058931/81425372-7884ad80-9125-11ea-8316-e8209a2de37c.png)

**Comment by akatechis** [comment]
Did a little more digging, looks like this is intended as a placeholder? If so, you might want to put a "coming soon" message of some sort, otherwise, I suspect lots of other people will have the same reaction

**Comment by cofibrant** [comment]
Sorry yeah it’s a placeholder... I’ll add a notice!
